spring.application.name=Campus-Connect
server.address=0.0.0.0
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_connect
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=4m9Pz7QaX2nL8wYc6JdE3fBg9NpTuWxZaC7LmQrVvRt5HsK1
jwt.expiration=
