spring.application.name=Campus-Connect
server.address=0.0.0.0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=jdbc:mysql://localhost:3306/campus_connect
spring.datasource.username=root
spring.datasource.password=accidental.nitians

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true